export const MIME_TYPES: Record<string, string> = {
  html: "text/html",
  htm: "text/html",
  shtml: "text/html",
  css: "text/css",
  csv: "text/csv",
  txt: "text/plain",
  text: "text/plain",
  md: "text/markdown",
  markdown: "text/markdown",
  xml: "application/xml",
  yaml: "application/x-yaml",
  yml: "application/x-yaml",

  json: "application/json",
  map: "application/json",
  webmanifest: "application/manifest+json",

  js: "application/javascript",
  mjs: "application/javascript",
  cjs: "application/javascript",
  ts: "application/typescript",
  jsx: "application/javascript",
  tsx: "application/javascript",

  png: "image/png",
  apng: "image/apng",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  jfif: "image/jpeg",
  pjg: "image/jpeg",
  pjpeg: "image/jpeg",
  gif: "image/gif",
  bmp: "image/bmp",
  webp: "image/webp",
  svg: "image/svg+xml",
  ico: "image/x-icon",
  tif: "image/tiff",
  tiff: "image/tiff",
  avif: "image/avif",
  heic: "image/heic",

  mp3: "audio/mpeg",
  wav: "audio/wav",
  ogg: "audio/ogg",
  m4a: "audio/mp4",
  aac: "audio/aac",
  flac: "audio/flac",
  midi: "audio/midi",

  mp4: "video/mp4",
  mpeg: "video/mpeg",
  mpg: "video/mpeg",
  webm: "video/webm",
  ogv: "video/ogg",
  avi: "video/x-msvideo",
  mov: "video/quicktime",
  mkv: "video/x-matroska",

  woff: "font/woff",
  woff2: "font/woff2",
  ttf: "font/ttf",
  otf: "font/otf",
  eot: "application/vnd.ms-fontobject",

  zip: "application/zip",
  tar: "application/x-tar",
  gz: "application/gzip",
  tgz: "application/gzip",
  rar: "application/vnd.rar",
  "7z": "application/x-7z-compressed",

  pdf: "application/pdf",
  doc: "application/msword",
  dot: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  rtf: "application/rtf",

  form: "application/x-www-form-urlencoded",
  urlencoded: "application/x-www-form-urlencoded",
  multipart: "multipart/form-data",
  wasm: "application/wasm",
  graphql: "application/graphql",
  ndjson: "application/x-ndjson",
  rss: "application/rss+xml",
  atom: "application/atom+xml",

  bin: "application/octet-stream",
  exe: "application/octet-stream",
  dll: "application/octet-stream",
};
